apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
  namespace: errick
provisioner: ebs.csi.aws.com
# provisioner: k8s.io/minikube-hostpath 
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

