apiVersion: v1
kind: Service
metadata:
  name: twoge-app-service
  namespace: errick
spec:
  type: NodePort
  ports:
  - port: 80 #the port the service listens on
    targetPort: 80 #forward traffic to this port 
    nodePort: 30080 #makes the application accessible from outside the cluster on port 30080 of any node
  selector:
    app: twoge-app